[versions]
kotlin = "1.7.20"
kordex = "1.5.5-20221019.205922-33"

detekt = "1.21.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kordex = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kordex" }
