contact_links:
  - name: Find support in the HyacinthBots discord!
    url: https://discord.gg/hy2329fcTZ
    about: This library was written initially for use within LilyBot, a bot made at Hyacinth, both lead developers know how to use this library and can support you from there!
